default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: leobeirouti
  password: 123456
  host: localhost

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
  username: leobeirouti
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>